### PR TITLE
concernedtater

### PR DESCRIPTION
**Pull request by nnym**
big concern
https://streamable.com/1fhe7v
image

### CODE REVIEW

**Review by ramidzkh — APPROVED** [review]

**Comment by Yoghurt4C** [comment]
no

**Comment by Yoghurt4C** [comment]
thanks for the resolved dep though :ant::ant::ant:

**Comment by nnym** [comment]
What does that label mean?

**Comment by Yoghurt4C** [comment]
it's highly unlikely that this pr would survive the stalebot, considering I'm not finding a single thing I like about it sans https://github.com/Yoghurt4C/LilTaterReloaded/pull/5/commits/ac397e3b7032c57bd24123a762d980ba7f69dd5e;
personally, I'd prefer to close this and implement data-driven equivalents to *some* of these features down the road (in this instance, equipment-based skins)

**Comment by nnym** [comment]
So "snusk" means "filth" in Swedish according to a search result that I got.

**Comment by Yoghurt4C** [comment]
yes.

**Pull request closed without merging**
